# Generated by Django 5.0.4 on 2024-05-19 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_version"),
    ]

    operations = [
        migrations.AlterField(
            model_name="version",
            name="is_active",
            field=models.BooleanField(
                default=False, verbose_name="признак текущей версии"
            ),
        ),
    ]
