# Generated by Django 4.2.2 on 2024-05-28 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "permissions": [
                    ("can_edit_category", "Can edit category"),
                    ("can_edit_description_product", "Can edit description product"),
                    ("can_edit_is_published", "Can edit is published"),
                ],
                "verbose_name": "Товар",
                "verbose_name_plural": "Товары",
            },
        ),
    ]
